# Final Project

## IMPORTING LIBRARIES

In [41]:
import pandas as pd

## IMPORTING DATA SET

In [79]:
covid = pd.read_csv("CovidDataSet.csv")

In [80]:
covid.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-02-08 05:22:39,33.93911,67.709953,55335,2410,48041,4884.0,Afghanistan,142.145796,4.355291
1,NaN,NaN,NaN,Albania,2021-02-08 05:22:39,41.15330,20.168300,85336,1460,51444,32432.0,Albania,2965.320731,1.710884
2,NaN,NaN,NaN,Algeria,2021-02-08 05:22:39,28.03390,1.659600,109088,2914,74692,31482.0,Algeria,248.769453,2.671238
3,NaN,NaN,NaN,Andorra,2021-02-08 05:22:39,42.50630,1.521800,10251,106,9533,612.0,Andorra,13267.326733,1.034045
4,NaN,NaN,NaN,Angola,2021-02-08 05:22:39,-11.20270,17.873900,20086,475,18540,1071.0,Angola,61.114332,2.364831

### RE-CODING "FIPS" COLUMN TO REFLECT ONLY ADDRESSES IN ARIZONA AND NEW MEXICO
#### STILL NEED TO CONFIRM IF THE LIST WE HAVE INCLUDES ALL THE COUNTIES IN THE STATES BEING PULLED FROM

In [81]:
covid2 = covid[covid["FIPS"].isin([4001, 4003, 4005, 4007, 4009, 4011, 4012, 4013, 4015, 4017, 4019, 4021, 4023, 4025,4027,35001, 35003, 35005, 35006, 35007, 35009, 35011, 35013, 35015, 35017, 35019, 35021, 35023, 35025, 35027, 35028, 35029, 35031, 35033, 35035, 35037, 35039, 35041, 35045, 35047, 35043, 35049, 35051, 35053, 35055, 35057, 35059, 35061])]

In [78]:
covid2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 749 to 2522
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   FIPS                 48 non-null     float64
 1   Admin2               48 non-null     object
 2   Province_State       48 non-null     object
 3   Country_Region       48 non-null     object
 4   Last_Update          48 non-null     object
 5   Lat                  48 non-null     float64
 6   Long_                48 non-null     float64
 7   Confirmed            48 non-null     int64
 8   Deaths               48 non-null     int64
 9   Recovered            48 non-null     int64
 10  Active               48 non-null     float64
 11  Combined_Key         48 non-null     object
 12  Incident_Rate        48 non-null     float64
 13  Case_Fatality_Ratio  48 non-null     float64
 14  Navajo               0 non-null      object
dtypes: float64(6), int64(3), object(6)
memory usage: 6.0+ KB

In [46]:
covid2.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
749,4001.0,Apache,Arizona,US,2021-02-08 05:22:39,35.394650,-109.489238,9854,326,0,9528.0,"Apache, Arizona, US",13707.624466,3.308301
750,4003.0,Cochise,Arizona,US,2021-02-08 05:22:39,31.879347,-109.751609,10602,238,0,10364.0,"Cochise, Arizona, US",8419.497784,2.244859
751,4005.0,Coconino,Arizona,US,2021-02-08 05:22:39,35.838834,-111.770718,15675,288,0,15387.0,"Coconino, Arizona, US",10925.172154,1.837321
752,4007.0,Gila,Arizona,US,2021-02-08 05:22:39,33.801901,-110.813278,6159,199,0,5960.0,"Gila, Arizona, US",11401.754971,3.231044
753,4009.0,Graham,Arizona,US,2021-02-08 05:22:39,32.931669,-109.888218,5158,69,0,5089.0,"Graham, Arizona, US",13281.149419,1.337728

In [47]:
covid2.tail()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
2517,35053.0,Socorro,New Mexico,US,2021-02-08 05:22:39,34.007155,-106.929835,1165,47,0,1118.0,"Socorro, New Mexico, US",7002.464387,4.034335
2518,35055.0,Taos,New Mexico,US,2021-02-08 05:22:39,36.580060,-105.631020,1468,46,0,1422.0,"Taos, New Mexico, US",4486.141246,3.133515
2519,35057.0,Torrance,New Mexico,US,2021-02-08 05:22:39,34.640484,-105.850895,610,12,0,598.0,"Torrance, New Mexico, US",3945.411034,1.967213
2521,35059.0,Union,New Mexico,US,2021-02-08 05:22:39,36.481264,-103.470962,212,8,0,204.0,"Union, New Mexico, US",5222.961321,3.773585
2522,35061.0,Valencia,New Mexico,US,2021-02-08 05:22:39,34.716698,-106.810373,5919,86,0,5833.0,"Valencia, New Mexico, US",7718.287085,1.452948

In [82]:
 def FIPS (series): 
    if series == 4003:
        return 0
    if series == 4001: 
        return 1
    if series == 40012:
        return 0
    if series == 4005: 
        return 1
    if series == 40012:
        return 0
    if series == 4005: 
        return 1
    if series == 4007:
        return 0
    if series == 4017: 
        return 1
    if series == 35006:
        return 0
    if series == 35031: 
        return 1
    if series == 35001:
        return 0
    if series == 35045: 
        return 1
    if series == 35001:
        return 0
    if series == 35045: 
        return 1
    if series == 4012:
        return 0
    if series == 4013: 
        return 0
    if series == 4015:
        return 0
    if series == 4019: 
        return 0
    if series == 4021:
        return 0
    if series == 4023: 
        return 0
    if series == 4025:
        return 0
    if series == 4027: 
        return 0
    if series == 35029:
        return 0
    if series == 35003: 
        return 0
    if series == 35028:
        return 0
    if series == 35033: 
        return 0
    if series == 35035:
        return 0
    if series == 35013: 
        return 0
    if series == 35011:
        return 0
    if series == 35009: 
        return 0
    if series == 35039:
        return 0
    if series == 35007: 
        return 0
    if series == 35028:
        return 0
    if series == 35017: 
        return 0
    if series == 35027:
        return 0
    if series == 35025: 
        return 0
    if series == 35015:
        return 0
    if series == 35019: 
        return 0
    if series == 35021:
        return 0
    if series == 35037: 
        return 0
    if series == 35047:
        return 0
    if series == 35043: 
        return 0
    if series == 35049:
        return 0
    if series == 35051: 
        return 0
    if series == 35053:
        return 0
    if series == 35055: 
        return 0
    if series == 35057:
        return 0
    if series == 90035: 
        return 0
    if series == 35059:
        return 0
    if series == 35061: 
        return 0

In [83]:
covid2['Navajo'] = covid2['FIPS'].apply(FIPS)

<ipython-input-83-f755f739a500>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid2['Navajo'] = covid2['FIPS'].apply(FIPS)

In [84]:
covid2.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Navajo
749,4001.0,Apache,Arizona,US,2021-02-08 05:22:39,35.394650,-109.489238,9854,326,0,9528.0,"Apache, Arizona, US",13707.624466,3.308301,1.0
750,4003.0,Cochise,Arizona,US,2021-02-08 05:22:39,31.879347,-109.751609,10602,238,0,10364.0,"Cochise, Arizona, US",8419.497784,2.244859,0.0
751,4005.0,Coconino,Arizona,US,2021-02-08 05:22:39,35.838834,-111.770718,15675,288,0,15387.0,"Coconino, Arizona, US",10925.172154,1.837321,1.0
752,4007.0,Gila,Arizona,US,2021-02-08 05:22:39,33.801901,-110.813278,6159,199,0,5960.0,"Gila, Arizona, US",11401.754971,3.231044,0.0
753,4009.0,Graham,Arizona,US,2021-02-08 05:22:39,32.931669,-109.888218,5158,69,0,5089.0,"Graham, Arizona, US",13281.149419,1.337728,NaN

In [85]:
pd.options.display.max_columns = 1000

In [87]:
covid2.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Navajo
749,4001.0,Apache,Arizona,US,2021-02-08 05:22:39,35.394650,-109.489238,9854,326,0,9528.0,"Apache, Arizona, US",13707.624466,3.308301,1.0
750,4003.0,Cochise,Arizona,US,2021-02-08 05:22:39,31.879347,-109.751609,10602,238,0,10364.0,"Cochise, Arizona, US",8419.497784,2.244859,0.0
751,4005.0,Coconino,Arizona,US,2021-02-08 05:22:39,35.838834,-111.770718,15675,288,0,15387.0,"Coconino, Arizona, US",10925.172154,1.837321,1.0
752,4007.0,Gila,Arizona,US,2021-02-08 05:22:39,33.801901,-110.813278,6159,199,0,5960.0,"Gila, Arizona, US",11401.754971,3.231044,0.0
753,4009.0,Graham,Arizona,US,2021-02-08 05:22:39,32.931669,-109.888218,5158,69,0,5089.0,"Graham, Arizona, US",13281.149419,1.337728,NaN

In [88]:
covid2.Navajo.value_counts()

0.0    38
1.0     5
Name: Navajo, dtype: int64